build: move source under src/ and fix out-of-tree builds
By moving everything under `src/update_engine` we can get rid of `-I..`
and the assumption that the top level directory is always named
`update_engine`. This makes it possible to fix up out-of-tree builds:

    mkdir build
    cd build
    ../configure
    make

diff --git a/run_unittests_as_root b/run_unittests_as_root
--- a/run_unittests_as_root
+++ b/run_unittests_as_root
@@ -9,4 +9,20 @@ if [[ "$(id -u)" -ne 0 ]]; then
         exit 77
     fi
 fi
+
+if ! [[ -f unittest_key.pub.pem || -f unittest_key2.pub.pem ]]; then
+    echo "ERROR: tests much run in the build output directory" >&2
+    exit 99
+fi
+
+# If running in an out-of-tree build grab the private test keys
+if ! [[ -f unittest_key.pem && -f unittest_key2.pem ]]; then
+    srcdir="$(dirname "$0")"
+    cp "${srcdir}/unittest_key.pem" "${srcdir}/unittest_key2.pem" ./
+    if [[ $? -ne 0 ]]; then
+        echo "ERROR: failed to copy private test keys to build directory" >&2
+        exit 99
+    fi
+fi
+
 $sudo ./update_engine_unittests --gtest_filter='*.RunAsRoot*'
