Reflect return status of each invocation of a set of tests.
BUG=None
TEST=Unit tests invoked and status reported properly.

Change-Id: I55dfa306ffea607bd56ed6e461bc8c3f4df30863
Reviewed-on: https://gerrit.chromium.org/gerrit/26725
Reviewed-by: Don Garrett <dgarrett@chromium.org>
Commit-Ready: Gilad Arnold <garnold@chromium.org>
Tested-by: Gilad Arnold <garnold@chromium.org>

diff --git a/run_unittests b/run_unittests
--- a/run_unittests
+++ b/run_unittests
@@ -12,5 +12,10 @@ if [ ! -e ./update_engine_unittests ]; then
   exit 1
 fi
 
-./update_engine_unittests --gtest_filter='-*.RunAsRoot*'
-sudo ./update_engine_unittests --gtest_filter='*.RunAsRoot*'
+user_pass=0
+./update_engine_unittests --gtest_filter='-*.RunAsRoot*' && user_pass=1
+root_pass=0
+sudo ./update_engine_unittests --gtest_filter='*.RunAsRoot*' && root_pass=1
+
+echo -n "User tests: " && [ $user_pass == 1 ] && echo "PASSED" || echo "FAILED"
+echo -n "Root tests: " && [ $root_pass == 1 ] && echo "PASSED" || echo "FAILED"
